### ISSUE TITLE
Processing page provide real time feedback on progress

### ISSUE THREAD

**Issue by jongund** [opena11y/fae-ainspector#1]
Add to processing page the number of pages that have been processed in real time.

Important for users to see that something is happening, especially for reports with a large number of pages

**Comment by jongund** [comment]
Added number of pages that have been processed tot he status area and added a "role=status" to the table cell so that it will be automatically read to screen readers.

**Comment by jongund** [comment]
Available on development server

**Comment by clblew** [comment]
Just ran new report on DRES. This feature is working well. Figured it would move faster, yet it does provide that visual element so that you do not question if the page is working or not.
