### ISSUE TITLE
Registration e-mail: Incorrect URL returned for verifying account

### ISSUE THREAD

**Issue by jongund** [opena11y/fae-ainspector#2]
From Christy:

Creating an account – FORM PAGE GOOD. GOT A CONFIRMATION EMAIL. (To complete Step 2, the last step of your registration, please select the following link within the next 7 days:    localhost:8000/accounts/activate/aa7efd7c9b8500a90a32007fed9c716a259b0fa9/) Assume the localhost URL is because it is dev server, therefore cannot test account after confirmation

**Comment by jongund** [comment]
Fixed the URL problem my updating a filed in the database used by the URL

**Comment by clblew** [comment]
Retested creating an account. Seems that my account I tried to do the other day must have saved even though I didn't confirm the email as it said that account already existed. registered account with my personal email. Was able to complete confirmation and then login with no problems.
