### ISSUE TITLE
Scan depth

### ISSUE THREAD

**Issue by timo54** [opena11y/fae-ainspector#24]
FAE doesn't scan all the pages when the scan depth is set to 2 or 3. It will scan 5-6 pages and then submits the report even though the site being scanned has dozens of pages. 
I was scanning the Champaign County Regional Planning Commission web site (http://www.ccrpc.org/ccrpc/index.php) and the report generated is at http://fae20.cita.illinois.edu/summary/14d5fc67979fae66/rc/.

**Comment by jongund** [comment]
The web site now generates a multi-page report with FAE version 0.9.7:

HTML5 and ARIA:
http://fae20.cita.illinois.edu/summary/14eff54e0fd1320b/rc/ 
 
MTHML 4:
http://fae20.cita.illinois.edu/summary/14eff5a1771f9427/rc/

**Comment by timo54** [comment]
Thanks Jon.

-Tim
