### ISSUE TITLE
Can't view reports

### ISSUE THREAD

**Issue by BenEhlers** [opena11y/fae-ainspector#35]
Reports are stuck on the processing page, I can not manage or view them? Status says "Saving results: 1 page evaluated"

**Comment by jongund** [comment]
SHould be working now, retry the URL

**Comment by agchiles** [comment]
Hi Jon--I'm having the same problem.  My report is stuck "Saving results."  I've tried running smaller sites with a shorter depth and logging out and back in, but now all four URLs I have tried are stuck there and I can't view the full reports.

**Comment by agchiles** [comment]
It's working now.  Thanks Jon.

**Comment by Falkohol** [comment]
I'm having the same Problem. Not working since yesterday...

**Comment by jongund** [comment]
Should be working now.  It might take a little while for it to catch up on processing report requests.
