### ISSUE TITLE
Invalid URL also if not true

### ISSUE THREAD

**Issue by fede91it** [opena11y/fae-ainspector#36]
TOOL: FAE 2.0

RULESET: HTML5/ARIA Techniques

DESCRIPTION: The url https://www.fineco.it/it/public is not redirected but FAE says that is an invalid URL and skip its processing.

URL: https://www.fineco.it/it/public

**Comment by jongund** [comment]
It looks like there is Javascript code on the page that HTMLUnit is not able to process, typically due to many code exceptions during execution.

You can use AInspector Sidebar (e.g. uses same OpenAjax Evaluation Library) to analyze the pages:
http://ainspector.github.io/
