### ISSUE TITLE
FAE 2.0 Report Processing Stuck on Saving Results

### ISSUE THREAD

**Issue by TylaTaylor** [opena11y/fae-ainspector#37]
TOOL: (FAE 2.0)

RULESET: (HTML5/ARIA Techniques or HTML4 Legacy Techniques)

DESCRIPTION: I now have tried running the FAE on the same URL 3 times over the past day and they are all stuck in "Saving Results"

URL: (http://fae20.cita.illinois.edu/reports/processing/)

STEPS TO REPRODUCE: (I filled in the form for starting a evaluation with these inputs: 	http://uiclibrary.pixotech.com/ to include third level pages, in the specified domain only with HTML5 and ARIA ruleset)

![screen shot 2016-06-22 at 9 10 42 am](https://cloud.githubusercontent.com/assets/11427313/16269787/71302330-3859-11e6-99ad-93dbdb9775bd.png)

**Comment by jongund** [comment]
The processing of reports has been restarted but it might take an hour or so for it to catch up.
come back in about an hour and the reports should be done

**Comment by TylaTaylor** [comment]
Thanks for looking into it so quickly Jon! I will check back in an hour.

Thanks again!
